/**
 * Copyright 2018 LinkedIn Corp. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.github.ambry.cloud;

import com.github.ambry.account.CloudReplicationConfig;

public interface CloudDestinationFactory {

  /**
   * @return an instance of {@link CloudDestination} generated by this factory.
   * @param config the {@link CloudReplicationConfig} for the destination to be created.
   * @throws InstantiationException if the {@link CloudDestination} instance cannot be created.
   */
  CloudDestination getCloudDestination(CloudReplicationConfig config) throws InstantiationException;
}
