package com.github.ambry.cloud;

import com.github.ambry.account.CloudReplicationConfig;


public interface CloudDestinationFactory {

  /**
   * @return an instance of {@link CloudDestination} generated by this factory.
   * @param config the {@link CloudReplicationConfig} for the destination to be created.
   * @throws InstantiationException if the {@link CloudDestination} instance cannot be created.
   */
  CloudDestination getCloudDestination(CloudReplicationConfig config) throws InstantiationException;
}
