package com.github.ambry.store;

public enum BlobStateMatchStatus {
  BLOB_STATE_MATCH,
  BLOB_STATE_NULL,
  BLOB_STATE_CLASS_MISMATCH,
  BLOB_STATE_KEY_MISMATCH,
  BLOB_STATE_SIZE_MISMATCH,
  BLOB_STATE_EXPIRY_MISMATCH,
  BLOB_STATE_DELETE_MISMATCH,
  BLOB_STATE_CRC_MISMATCH,
  BLOB_STATE_VERSION_MISMATCH
}