package com.github.ambry.rest;

/**
 * BlobStorageServiceFactory is a factory to generate all the supporting cast required to instantiate a
 * {@link BlobStorageService}.
 * <p/>
 * Usually called with the canonical class name and as such might have to support appropriate (multiple) constructors.
 */
public interface BlobStorageServiceFactory {

  /**
   * Returns a new instance of the {@link BlobStorageService} that the factory generates.
   * @return an instance of {@link BlobStorageService} generated by this factory.
   * @throws InstantiationException if the {@link BlobStorageService} instance cannot be created.
   */
  public BlobStorageService getBlobStorageService()
      throws InstantiationException;
}
