package com.github.ambry.rest;

/**
 * IdConverterFactory is a factory to generate all the supporting cast required to instantiate a {@link IdConverter}.
 * <p/>
 * Usually called with the canonical class name and as such might have to support appropriate (multiple) constructors.
 */
public interface IdConverterFactory {

  /**
   * Returns an instance of the {@link IdConverter} that the factory generates.
   * @return an instance of {@link IdConverter} generated by this factory.
   * @throws InstantiationException if the {@link IdConverter} instance cannot be created.
   */
  public IdConverter getIdConverter()
      throws InstantiationException;
}
