package com.github.ambry.rest;

/**
 * RestResponseHandlerFactory is a factory to generate all the supporting cast required to instantiate a
 * {@link RestResponseHandler}.
 * <p/>
 * Usually called with the canonical class name and as such might have to support appropriate (multiple) constructors.
 */
public interface RestResponseHandlerFactory {

  /**
   * Returns an instance of the {@link RestResponseHandler} that the factory generates.
   * @return an instance of {@link RestResponseHandler} generated by this factory.
   * @throws InstantiationException if the {@link RestResponseHandler} instance cannot be created.
   */
  public RestResponseHandler getRestResponseHandler()
      throws InstantiationException;
}
