package com.github.ambry.rest;

/**
 * RestRequestHandlerFactory is a factory to generate all the supporting cast required to instantiate a
 * {@link RestRequestHandler}.
 * <p/>
 * Usually called with the canonical class name and as such might have to support appropriate (multiple) constructors.
 */
public interface RestRequestHandlerFactory {

  /**
   * Returns an instance of the {@link RestRequestHandler} that the factory generates.
   * @return an instance of {@link RestRequestHandler} generated by this factory.
   * @throws InstantiationException if the {@link RestRequestHandler} instance cannot be created.
   */
  public RestRequestHandler getRestRequestHandler()
      throws InstantiationException;
}
