package com.github.ambry.rest;

import com.codahale.metrics.MetricRegistry;
import com.github.ambry.config.VerifiableProperties;


/**
 *  SecurityServiceFactory is a factory to generate all the supporting cast required to instantiate a
 * {@link SecurityService}.
 * <p/>
 * Usually called with the canonical class name and as such might have to support appropriate (multiple) constructors.
 */
public interface SecurityServiceFactory {

  /**
   * Returns an instance of the {@link SecurityService} that the factory generates.
   * @param verifiableProperties the properties to use to create configs.
   * @param metricRegistry the {@link MetricRegistry} to use for the metrics.
   * @return an instance of {@link SecurityService} generated by this factory.
   * @throws InstantiationException if the {@link SecurityService} instance cannot be created.
   */
  public SecurityService getSecurityService(VerifiableProperties verifiableProperties, MetricRegistry metricRegistry)
      throws InstantiationException;
}
