/**
 * Copyright 2020 LinkedIn Corp. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package com.github.ambry.commons;

/**
 * Interface for creating throttler factory classes.
 */
public interface ThrottlerFactory {

  /**
   * Returns an instance of the {@link Throttler} that the factory generates.
   * @return an instance of the {@link Throttler} generated by this method.
   * @throws InstantiationException if the {@link Throttler} instance cannot be created.
   */
  Throttler getThrottler();
}
