package com.github.ambry.store;

/**
 * StoreKeyConverterFactory is a factory to generate all the supporting cast required to instantiate a
 * {@link StoreKeyConverter}.
 * <p/>
 * Usually called with the canonical class name and as such might have to support appropriate (multiple) constructors.
 */
public interface StoreKeyConverterFactory {

  /**
   * Returns an instance of the {@link StoreKeyConverter} that the factory generates.
   * @return an instance of {@link StoreKeyConverter} generated by this factory.
   * @throws InstantiationException if the {@link StoreKeyConverter} instance cannot be created.
   */
  StoreKeyConverter getStoreKeyConverter() throws InstantiationException;
}